-- Apply explicitly to live Postgres.  Idempotent schema bootstrap for the
-- daily decision/outreach pipeline; SQLAlchemy create_all does not migrate.
CREATE TABLE IF NOT EXISTS job_posting_versions (id SERIAL PRIMARY KEY, job_id INTEGER NOT NULL REFERENCES jobs(id), canonical_duplicate_root_id INTEGER NOT NULL REFERENCES jobs(id), posted_at TIMESTAMPTZ, material_content_hash VARCHAR(64) NOT NULL, posting_instance_key VARCHAR(128) NOT NULL UNIQUE, snapshot JSON NOT NULL, first_seen_at TIMESTAMPTZ NOT NULL, last_seen_at TIMESTAMPTZ NOT NULL);
CREATE TABLE IF NOT EXISTS job_applications (id SERIAL PRIMARY KEY, posting_version_id INTEGER NOT NULL UNIQUE REFERENCES job_posting_versions(id), canonical_duplicate_root_id INTEGER NOT NULL REFERENCES jobs(id), applied_at TIMESTAMPTZ NOT NULL, source VARCHAR(100), job_url_snapshot VARCHAR(1000), tailored_resume_id INTEGER REFERENCES tailored_resumes(id), notes TEXT);
CREATE TABLE IF NOT EXISTS job_screening_facts (id SERIAL PRIMARY KEY, posting_version_id INTEGER NOT NULL REFERENCES job_posting_versions(id), extraction_version VARCHAR(50) NOT NULL DEFAULT '1', salary JSON, minimum_experience JSON, maximum_experience JSON, extracted_at TIMESTAMPTZ NOT NULL, evidence_hash VARCHAR(64), UNIQUE(posting_version_id, extraction_version));
CREATE TABLE IF NOT EXISTS decision_runs (id VARCHAR(64) PRIMARY KEY, since_at TIMESTAMPTZ NOT NULL, cutoff_at TIMESTAMPTZ NOT NULL, input_timezone VARCHAR(100) NOT NULL, state VARCHAR(30) NOT NULL, policy_snapshot JSON NOT NULL, target_count INTEGER NOT NULL, created_at TIMESTAMPTZ NOT NULL, prepared_at TIMESTAMPTZ, approved_at TIMESTAMPTZ, completed_at TIMESTAMPTZ, failure_detail TEXT);
CREATE TABLE IF NOT EXISTS decision_run_jobs (id SERIAL PRIMARY KEY, run_id VARCHAR(64) NOT NULL REFERENCES decision_runs(id), posting_version_id INTEGER NOT NULL REFERENCES job_posting_versions(id), job_id INTEGER NOT NULL REFERENCES jobs(id), company_id INTEGER NOT NULL REFERENCES companies(id), outcome VARCHAR(30) NOT NULL, snapshot JSON NOT NULL, explicit_salary_lpa DOUBLE PRECISION, ambitionbox_salary_lpa DOUBLE PRECISION, effective_salary_lpa DOUBLE PRECISION, salary_source VARCHAR(30), role_family VARCHAR(40), work_mode VARCHAR(20), qualified_wlb DOUBLE PRECISION, review_count INTEGER, group_number INTEGER, within_company_rank INTEGER, is_primary BOOLEAN NOT NULL DEFAULT FALSE, UNIQUE(run_id, posting_version_id));
CREATE TABLE IF NOT EXISTS decision_run_findings (id SERIAL PRIMARY KEY, decision_run_job_id INTEGER NOT NULL REFERENCES decision_run_jobs(id), kind VARCHAR(30) NOT NULL, reason_code VARCHAR(80) NOT NULL, evidence TEXT, parsed_value VARCHAR(255), threshold VARCHAR(255), comparison VARCHAR(255), details JSON);
CREATE TABLE IF NOT EXISTS decision_run_companies (id SERIAL PRIMARY KEY, run_id VARCHAR(64) NOT NULL REFERENCES decision_runs(id), company_id INTEGER NOT NULL REFERENCES companies(id), group_number INTEGER, rank INTEGER, primary_run_job_id INTEGER REFERENCES decision_run_jobs(id), company_type VARCHAR(20) NOT NULL, outreach_success_count INTEGER NOT NULL DEFAULT 0, mode VARCHAR(40) NOT NULL DEFAULT 'ranked', UNIQUE(run_id, company_id), UNIQUE(run_id, group_number, rank));
CREATE TABLE IF NOT EXISTS decision_run_approvals (id SERIAL PRIMARY KEY, run_id VARCHAR(64) NOT NULL UNIQUE REFERENCES decision_runs(id), original_text TEXT NOT NULL, normalized_rules JSON NOT NULL, target_count INTEGER NOT NULL, approver VARCHAR(255), approved_at TIMESTAMPTZ NOT NULL);
CREATE TABLE IF NOT EXISTS decision_run_selected_jobs (id SERIAL PRIMARY KEY, run_id VARCHAR(64) NOT NULL REFERENCES decision_runs(id), company_id INTEGER NOT NULL REFERENCES companies(id), posting_version_id INTEGER NOT NULL REFERENCES job_posting_versions(id), company_order INTEGER NOT NULL, selection_kind VARCHAR(30) NOT NULL, UNIQUE(run_id, posting_version_id));
CREATE TABLE IF NOT EXISTS outreach_messages (id SERIAL PRIMARY KEY, legacy_draft_id INTEGER UNIQUE REFERENCES outreach_drafts(id), run_id VARCHAR(64) REFERENCES decision_runs(id), company_id INTEGER NOT NULL REFERENCES companies(id), contact_id INTEGER REFERENCES contacts(id), decision_run_job_id INTEGER REFERENCES decision_run_jobs(id), posting_version_id INTEGER REFERENCES job_posting_versions(id), message_kind VARCHAR(20) NOT NULL DEFAULT 'initial', is_calibration BOOLEAN NOT NULL DEFAULT FALSE, subject TEXT NOT NULL, body TEXT NOT NULL, resume_path VARCHAR(1000), pairing_reason VARCHAR(80), state VARCHAR(30) NOT NULL DEFAULT 'held', created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL, UNIQUE(run_id, contact_id, message_kind));
CREATE TABLE IF NOT EXISTS outreach_delivery_attempts (id SERIAL PRIMARY KEY, message_id INTEGER NOT NULL REFERENCES outreach_messages(id), sequence_number INTEGER NOT NULL, to_email VARCHAR(255) NOT NULL, domain VARCHAR(255) NOT NULL, pattern_name VARCHAR(30), gmail_draft_id VARCHAR(100), gmail_thread_id VARCHAR(100), gmail_message_id VARCHAR(100) UNIQUE, state VARCHAR(30) NOT NULL DEFAULT 'held', pushed_at TIMESTAMPTZ, sent_at TIMESTAMPTZ, presumed_delivered_at TIMESTAMPTZ, replied_at TIMESTAMPTZ, bounced_at TIMESTAMPTZ, evidence JSON, UNIQUE(message_id, sequence_number));
CREATE TABLE IF NOT EXISTS company_domain_aliases (id SERIAL PRIMARY KEY, company_id INTEGER NOT NULL REFERENCES companies(id), domain VARCHAR(255) NOT NULL, first_observed_at TIMESTAMPTZ NOT NULL, last_observed_at TIMESTAMPTZ NOT NULL, is_current BOOLEAN NOT NULL DEFAULT TRUE, is_verified BOOLEAN NOT NULL DEFAULT FALSE, UNIQUE(company_id, domain));
CREATE TABLE IF NOT EXISTS domain_email_patterns (id SERIAL PRIMARY KEY, domain VARCHAR(255) NOT NULL, pattern_name VARCHAR(30) NOT NULL, confidence VARCHAR(20) NOT NULL DEFAULT 'unknown', success_count INTEGER NOT NULL DEFAULT 0, reply_count INTEGER NOT NULL DEFAULT 0, bounce_count INTEGER NOT NULL DEFAULT 0, first_observed_at TIMESTAMPTZ, last_observed_at TIMESTAMPTZ, UNIQUE(domain, pattern_name));
CREATE TABLE IF NOT EXISTS run_company_calibrations (id SERIAL PRIMARY KEY, run_id VARCHAR(64) NOT NULL REFERENCES decision_runs(id), company_id INTEGER NOT NULL REFERENCES companies(id), domain VARCHAR(255), contact_id INTEGER REFERENCES contacts(id), message_id INTEGER REFERENCES outreach_messages(id), state VARCHAR(30) NOT NULL DEFAULT 'waiting_to_send', first_sent_at TIMESTAMPTZ, deadline_at TIMESTAMPTZ, confirmed_pattern VARCHAR(30), last_reconciled_at TIMESTAMPTZ, UNIQUE(run_id, company_id));
-- Baseline versions for existing jobs; run after deployment before first decision run.
-- Use the application's backfill command for hashes/snapshots so the key
-- exactly matches future upserts.
